# This is a basic workflow to help you get started with Actions

name: Run tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - name: Install & test
        run: |
          npm i -g pnpm
          pnpm i
          pnpm test
          
